// Code generated by sqlc. DO NOT EDIT.

package pg

import (
	"database/sql"
)

type IntersectingSet struct {
	ID                 int64
	SetUid             []byte
	IntersectingsetUid []byte
}

type Set struct {
	ID     int64
	SetUid []byte
}

type SetsData struct {
	ID     int64
	Data   sql.NullInt64
	SetUid []byte
}
