// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graph

type Set struct {
	Members          []int64 `json:"members"`
	IntersectingSets []Set   `json:"intersectingSets"`
}

type SetInput struct {
	Members []int64 `json:"members"`
}
